image: maven:3.8.5-openjdk-11

tasks:
  - init: mvn install -DskipTests=false

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - vivaxy.vscode-conventional-commits
    - redhat.vscode-xml
