language: java

sudo: false

jdk: openjdk8

script: mvn clean install -Pcoverage sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=qlack -Dsonar.projectName=Qlack-Java -Dsonar.login=a794de41120844d9bdc7547a961faffc6769f2c7

notifications:
  email:
    recipients:
      - qlack@eurodyn.com
    on_success: change
    on_failure: change
